import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { AuditReport, AuditFinding } from "@/lib/types/audit";

interface CostEstimateForPDF {
  total_penalty_exposure: number;
  total_remediation_cost: number;
  has_criminal_risk: boolean;
  breakdown: {
    jurisdiction: string;
    jurisdiction_display: string;
    max_penalty: number;
    remediation_cost: number;
    finding_count: number;
    has_criminal: boolean;
    enforcement_body: string;
    fine_basis: string;
  }[];
}

const SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"];
const SEVERITY_COLORS: Record<string, [number, number, number]> = {
  critical: [239, 68, 68],
  high: [249, 115, 22],
  medium: [234, 179, 8],
  low: [52, 211, 153],
  info: [34, 211, 238],
};

function formatCurrency(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
}

export function generateAuditPDF(
  report: AuditReport,
  costEstimate?: CostEstimateForPDF
): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const generatedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const addHeaderFooter = () => {
    const pn = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(139, 135, 184);
    doc.text(`Confidential — Generated ${generatedDate} by Complyze`, margin, 10);
    doc.text(`Page ${pn}`, pageWidth - margin, pageHeight - 10, { align: "right" });
    doc.text(`Data freshness: ${report.data_freshness || "N/A"}`, margin, pageHeight - 10);
  };

  // ── COVER PAGE ──
  doc.setFillColor(11, 10, 26);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setTextColor(129, 140, 248);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("COMPLYZE", pageWidth / 2, 50, { align: "center" });

  doc.setTextColor(226, 224, 240);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("AI Compliance Audit Report", pageWidth / 2, 75, { align: "center" });

  // Risk level badge
  const riskColor = SEVERITY_COLORS[report.risk_level] || [200, 200, 200];
  doc.setFontSize(16);
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(
    `Risk Level: ${report.risk_level.toUpperCase()}`,
    pageWidth / 2,
    95,
    { align: "center" }
  );

  doc.setDrawColor(129, 140, 248);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 30, 105, pageWidth / 2 + 30, 105);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 156, 192);
  doc.text(`Risk Score: ${report.overall_risk_score}/100`, pageWidth / 2, 115, { align: "center" });
  doc.text(`Generated: ${generatedDate}`, pageWidth / 2, 123, { align: "center" });
  doc.text(`Regulations Checked: ${report.regulations_checked}`, pageWidth / 2, 131, { align: "center" });
  doc.text(`Config Hash: ${report.config_hash?.slice(0, 16) || "N/A"}`, pageWidth / 2, 139, { align: "center" });

  doc.setFontSize(9);
  doc.setTextColor(139, 135, 184);
  doc.text("Generated by Complyze — complyze.dev", pageWidth / 2, pageHeight - 25, { align: "center" });

  // ── EXECUTIVE SUMMARY ──
  doc.addPage();
  addHeaderFooter();
  let y = margin;

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", margin, y + 5);
  y += 15;

  // Summary stats
  const severityCounts: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of report.findings) {
    severityCounts[f.severity] = (severityCounts[f.severity] || 0) + 1;
  }

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);

  const summaryRows = [
    ["Overall Risk Score", `${report.overall_risk_score}/100 (${report.risk_level.toUpperCase()})`],
    ["Total Findings", String(report.findings.length)],
    ["Critical", String(severityCounts.critical)],
    ["High", String(severityCounts.high)],
    ["Medium", String(severityCounts.medium)],
    ["Low", String(severityCounts.low)],
    ["Informational", String(severityCounts.info)],
    ["Jurisdictions Analyzed", String(report.jurisdiction_results.length)],
    ["Regulations Checked", String(report.regulations_checked)],
  ];

  if (costEstimate) {
    summaryRows.push(
      ["Total Penalty Exposure", formatCurrency(costEstimate.total_penalty_exposure)],
      ["Estimated Remediation Cost", formatCurrency(costEstimate.total_remediation_cost)]
    );
    if (costEstimate.has_criminal_risk) {
      summaryRows.push(["Criminal Risk", "YES — some jurisdictions carry criminal penalties"]);
    }
  }

  autoTable(doc, {
    startY: y,
    body: summaryRows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3, textColor: [40, 40, 40], lineColor: [200, 200, 200], lineWidth: 0.25 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 55 } },
    theme: "plain",
    didDrawPage: () => addHeaderFooter(),
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable?.finalY + 10 || y + 60;

  // Top critical findings
  const criticalFindings = report.findings
    .filter((f) => f.severity === "critical" || f.severity === "high")
    .slice(0, 5);

  if (criticalFindings.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Top Priority Findings", margin, y);
    y += 7;

    for (const f of criticalFindings) {
      if (y > pageHeight - 30) { doc.addPage(); addHeaderFooter(); y = margin; }
      const color = SEVERITY_COLORS[f.severity] || [40, 40, 40];
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(color[0], color[1], color[2]);
      doc.text(`[${f.severity.toUpperCase()}]`, margin, y);
      doc.setTextColor(40, 40, 40);
      doc.text(f.title, margin + 22, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const desc = doc.splitTextToSize(f.description, contentWidth - 22);
      doc.text(desc, margin + 22, y);
      y += desc.length * 3.5 + 3;
    }
  }

  // ── JURISDICTION BREAKDOWN ──
  doc.addPage();
  addHeaderFooter();
  y = margin;

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Jurisdiction Breakdown", margin, y + 5);
  y += 15;

  for (const jr of report.jurisdiction_results) {
    if (y > pageHeight - 40) { doc.addPage(); addHeaderFooter(); y = margin; }

    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50, 50, 50);
    doc.text(`${jr.jurisdiction_display} (${jr.jurisdiction})`, margin, y);
    y += 6;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    doc.text(
      `Compliance: ${jr.compliance_score}% | Status: ${jr.status.replace("_", " ")} | Regulations: ${jr.applicable_regulations} | Critical: ${jr.critical_findings}`,
      margin,
      y
    );
    y += 6;

    // Findings table for this jurisdiction
    const jFindings = report.findings
      .filter((f) => f.jurisdiction === jr.jurisdiction)
      .sort((a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity));

    if (jFindings.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [["Severity", "Finding", "Regulation", "Config Ref"]],
        body: jFindings.map((f) => [
          f.severity.toUpperCase(),
          f.title.slice(0, 60),
          f.regulation_title.slice(0, 40),
          f.config_reference.slice(0, 30),
        ]),
        margin: { left: margin, right: margin },
        styles: { fontSize: 7, cellPadding: 2, textColor: [40, 40, 40], lineColor: [200, 200, 200], lineWidth: 0.25 },
        headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 245, 255] },
        didDrawPage: () => addHeaderFooter(),
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      y = (doc as any).lastAutoTable?.finalY + 8 || y + 20;
    } else {
      y += 4;
    }
  }

  // ── DETAILED FINDINGS ──
  doc.addPage();
  addHeaderFooter();
  y = margin;

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Detailed Findings", margin, y + 5);
  y += 15;

  const sortedFindings = [...report.findings].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );

  for (const finding of sortedFindings) {
    const blockHeight = 35;
    if (y + blockHeight > pageHeight - 20) { doc.addPage(); addHeaderFooter(); y = margin; }

    const color = SEVERITY_COLORS[finding.severity] || [40, 40, 40];

    // Severity + title
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(`[${finding.severity.toUpperCase()}]`, margin, y);
    doc.setTextColor(30, 30, 30);
    const titleText = doc.splitTextToSize(finding.title, contentWidth - 22);
    doc.text(titleText, margin + 22, y);
    y += titleText.length * 4 + 1;

    // Description
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(60, 60, 60);
    const descLines = doc.splitTextToSize(finding.description, contentWidth - 4);
    if (y + descLines.length * 3.5 > pageHeight - 20) { doc.addPage(); addHeaderFooter(); y = margin; }
    doc.text(descLines, margin + 2, y);
    y += descLines.length * 3.5 + 2;

    // Metadata
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    if (finding.regulation_title) {
      doc.text(`Regulation: ${finding.regulation_title} | ${finding.source_url || ""}`, margin + 2, y);
      y += 3.5;
    }
    if (finding.requirement) {
      const reqLines = doc.splitTextToSize(`Requirement: ${finding.requirement}`, contentWidth - 4);
      doc.text(reqLines, margin + 2, y);
      y += reqLines.length * 3 + 1;
    }
    if (finding.remediation) {
      doc.setTextColor(50, 120, 50);
      const remLines = doc.splitTextToSize(`Remediation: ${finding.remediation}`, contentWidth - 4);
      if (y + remLines.length * 3 > pageHeight - 20) { doc.addPage(); addHeaderFooter(); y = margin; }
      doc.text(remLines, margin + 2, y);
      y += remLines.length * 3 + 1;
    }

    y += 4;
  }

  // ── COST ANALYSIS ──
  if (costEstimate && costEstimate.breakdown.length > 0) {
    doc.addPage();
    addHeaderFooter();
    y = margin;

    doc.setTextColor(30, 30, 30);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Cost Analysis", margin, y + 5);
    y += 15;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    doc.text(`Total Penalty Exposure: ${formatCurrency(costEstimate.total_penalty_exposure)}`, margin, y);
    y += 5;
    doc.text(`Estimated Remediation Cost: ${formatCurrency(costEstimate.total_remediation_cost)}`, margin, y);
    y += 5;
    if (costEstimate.total_remediation_cost > 0) {
      const roi = (costEstimate.total_penalty_exposure / costEstimate.total_remediation_cost).toFixed(1);
      doc.text(`Penalty-to-Remediation Ratio: ${roi}x`, margin, y);
      y += 5;
    }
    if (costEstimate.has_criminal_risk) {
      doc.setTextColor(239, 68, 68);
      doc.setFont("helvetica", "bold");
      doc.text("WARNING: Some jurisdictions carry criminal penalties", margin, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      y += 5;
    }
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["Jurisdiction", "Max Penalty", "Remediation", "Findings", "Criminal", "Enforcement"]],
      body: costEstimate.breakdown.map((b) => [
        b.jurisdiction_display,
        formatCurrency(b.max_penalty),
        formatCurrency(b.remediation_cost),
        String(b.finding_count),
        b.has_criminal ? "YES" : "No",
        b.enforcement_body,
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 2, textColor: [40, 40, 40], lineColor: [200, 200, 200], lineWidth: 0.25 },
      headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [245, 245, 255] },
      didDrawPage: () => addHeaderFooter(),
    });
  }

  // ── RECOMMENDATIONS ──
  if (report.recommendations.length > 0) {
    doc.addPage();
    addHeaderFooter();
    y = margin;

    doc.setTextColor(30, 30, 30);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Recommendations", margin, y + 5);
    y += 15;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);

    for (let i = 0; i < report.recommendations.length; i++) {
      if (y > pageHeight - 25) { doc.addPage(); addHeaderFooter(); y = margin; }
      const lines = doc.splitTextToSize(`${i + 1}. ${report.recommendations[i]}`, contentWidth - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 4 + 3;
    }
  }

  return doc;
}
