export interface SeedRegulation {
  title: string;
  jurisdiction: string;
  jurisdiction_display: string;
  status: "enacted" | "proposed" | "in_effect" | "under_review" | "repealed";
  category: "legislation" | "executive_order" | "framework" | "guidance" | "standard";
  summary: string;
  key_requirements: string[];
  compliance_implications: string[];
  effective_date: string | null;
  source_url: string;
  source_name: string;
  ai_classified: boolean;
  ai_confidence: number | null;
}

export const seedRegulations: SeedRegulation[] = [
  // ================================================================
  // A. AI-SPECIFIC LEGISLATION
  // ================================================================
  {
    title: "EU Artificial Intelligence Act (Regulation 2024/1689)",
    jurisdiction: "EU",
    jurisdiction_display: "European Union",
    status: "enacted",
    category: "legislation",
    summary: "The world's first comprehensive AI law establishing a risk-based regulatory framework. Classifies AI systems into unacceptable, high, limited, and minimal risk tiers with corresponding obligations. Prohibits social scoring, real-time biometric surveillance (with exceptions), and manipulative AI.",
    key_requirements: [
      "Risk classification of AI systems into four tiers (unacceptable, high, limited, minimal)",
      "Mandatory conformity assessments for high-risk AI systems before market placement",
      "Transparency obligations: users must be informed when interacting with AI",
      "Human oversight requirements for high-risk AI decision-making",
      "Technical documentation and record-keeping for high-risk AI systems",
      "Post-market monitoring and incident reporting obligations",
      "General-purpose AI models must provide technical documentation and comply with EU copyright law",
    ],
    compliance_implications: [
      "Fines up to €35 million or 7% of global annual turnover for prohibited AI practices",
      "Fines up to €15 million or 3% of turnover for high-risk AI non-compliance",
      "Extraterritorial scope: applies to any AI system whose output is used within the EU",
    ],
    effective_date: "2026-08-02",
    source_url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    source_name: "Official Journal of the European Union",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Texas Responsible AI Governance Act (TRAIGA, HB 149)",
    jurisdiction: "US-TX",
    jurisdiction_display: "United States — Texas",
    status: "enacted",
    category: "legislation",
    summary: "Texas's comprehensive AI governance law regulating deployers of high-risk AI systems. Requires impact assessments, transparency disclosures, and human oversight for AI systems making consequential decisions in employment, housing, healthcare, education, financial services, and government.",
    key_requirements: [
      "Impact assessments required before deploying high-risk AI systems",
      "Transparency disclosures to individuals subject to AI-driven consequential decisions",
      "Right to opt out of AI-driven consequential decisions and request human review",
      "Annual governance reporting for deployers of high-risk AI systems",
      "Incident reporting for AI systems causing harm or discrimination",
    ],
    compliance_implications: [
      "Fines of $10,000 to $200,000 per violation enforced by the Texas Attorney General",
      "Applies to entities doing business in Texas regardless of where the AI system is developed",
    ],
    effective_date: "2026-01-01",
    source_url: "https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB149",
    source_name: "Texas Legislature Online",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Colorado AI Act (SB 24-205)",
    jurisdiction: "US-CO",
    jurisdiction_display: "United States — Colorado",
    status: "enacted",
    category: "legislation",
    summary: "Colorado's AI consumer protection law requiring developers and deployers of high-risk AI systems to use reasonable care to protect consumers from algorithmic discrimination. Enforcement delayed to June 30, 2026.",
    key_requirements: [
      "Developers must provide deployers with documentation on intended uses and risk of algorithmic discrimination",
      "Deployers must conduct impact assessments for high-risk AI systems before deployment",
      "Consumers must receive notice when a high-risk AI system makes a consequential decision about them",
      "Consumers have the right to opt out and request human alternative",
      "Disclosure to the Colorado Attorney General if algorithmic discrimination is discovered",
    ],
    compliance_implications: [
      "Enforced by Colorado Attorney General under the Colorado Consumer Protection Act",
      "Affirmative defense available for deployers who comply with recognized AI risk frameworks (e.g., NIST AI RMF)",
    ],
    effective_date: "2026-06-30",
    source_url: "https://leg.colorado.gov/bills/sb24-205",
    source_name: "Colorado General Assembly",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "NIST AI Risk Management Framework (AI RMF 1.0)",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "framework",
    summary: "Voluntary framework providing organizations with a structured approach to managing AI risks. Organized around four core functions: Govern, Map, Measure, and Manage. Widely referenced by US state AI laws as a safe harbor.",
    key_requirements: [
      "GOVERN: Establish AI risk management policies, roles, and organizational culture",
      "MAP: Contextualize AI system risks including intended and unintended uses",
      "MEASURE: Employ methods to analyze, assess, and track AI risks",
      "MANAGE: Prioritize and act on AI risks with resource allocation and response plans",
      "Documentation of AI system characteristics, limitations, and risk assessments",
    ],
    compliance_implications: [
      "Referenced as a recognized framework in Colorado AI Act (affirmative defense) and other state laws",
      "Voluntary but increasingly expected by regulators and enterprise customers as a baseline",
    ],
    effective_date: "2023-01-26",
    source_url: "https://www.nist.gov/artificial-intelligence/executive-order-safe-secure-and-trustworthy-artificial-intelligence",
    source_name: "National Institute of Standards and Technology",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Canada Artificial Intelligence and Data Act (AIDA, Bill C-27)",
    jurisdiction: "CA",
    jurisdiction_display: "Canada",
    status: "repealed",
    category: "legislation",
    summary: "Canada's proposed federal AI legislation that died on January 6, 2025, when PM Trudeau prorogued Parliament. Would have regulated high-impact AI systems. Canada currently has no dedicated federal AI legislation.",
    key_requirements: [
      "Would have required risk assessments for high-impact AI systems",
      "Would have mandated transparency measures including plain-language descriptions",
      "Would have created a new AI and Data Commissioner role",
      "Note: These requirements never came into force — the bill died",
    ],
    compliance_implications: [
      "No current dedicated AI legislation in Canada — bill died Jan 6, 2025",
      "PIPEDA and provincial privacy laws still govern AI data processing in Canada",
    ],
    effective_date: null,
    source_url: "https://www.parl.ca/legisinfo/en/bill/44-1/c-27",
    source_name: "Parliament of Canada",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Singapore Model AI Governance Framework for Generative AI and Agentic AI Systems",
    jurisdiction: "SG",
    jurisdiction_display: "Singapore",
    status: "in_effect",
    category: "framework",
    summary: "The world's first governance framework specifically addressing agentic AI systems, published by IMDA on January 22, 2026. Addresses unique risks of autonomous AI agents including multi-step actions, tool use, and delegated authority. Voluntary but influential across ASEAN.",
    key_requirements: [
      "Agentic AI systems must implement guardrails proportional to their level of autonomy",
      "Human oversight mechanisms required for high-stakes autonomous decisions",
      "Transparency: users must understand when interacting with an AI agent and what actions it can take",
      "Accountability frameworks must trace decisions back through agent chains",
      "Incident response plans specific to autonomous agent failures",
    ],
    compliance_implications: [
      "Voluntary framework but increasingly referenced in Singapore government procurement",
      "Framework provides a compliance baseline that may inform future mandatory regulation in ASEAN",
    ],
    effective_date: "2026-01-22",
    source_url: "https://www.imda.gov.sg/resources/press-releases-factsheets-and-speeches/press-releases/2026/new-model-ai-governance-framework-for-agentic-ai",
    source_name: "Infocomm Media Development Authority (IMDA)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "UK Pro-Innovation AI Regulation — Sectoral Approach and Forthcoming AI Bill",
    jurisdiction: "GB",
    jurisdiction_display: "United Kingdom",
    status: "under_review",
    category: "guidance",
    summary: "The UK's principles-based approach to AI regulation, delegating oversight to existing sector regulators. Five cross-cutting principles: safety, transparency, fairness, accountability, contestability. A formal AI Bill is anticipated in the May 2026 King's Speech.",
    key_requirements: [
      "Safety: AI systems must function securely, robustly, and as intended",
      "Transparency: AI systems must be appropriately transparent and explainable",
      "Fairness: AI must not undermine legal rights or discriminate unlawfully",
      "Accountability: Clear governance and oversight mechanisms must exist",
      "Contestability: Individuals must be able to challenge AI-driven decisions",
    ],
    compliance_implications: [
      "Currently principles-based and voluntary — mandatory AI Bill expected May 2026",
      "ICO enforcement of UK GDPR applies to AI systems processing personal data",
    ],
    effective_date: null,
    source_url: "https://www.gov.uk/government/publications/ai-regulation-a-pro-innovation-approach",
    source_name: "UK Department for Science, Innovation and Technology",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Brazil AI Bill (PL 2338/2023)",
    jurisdiction: "BR",
    jurisdiction_display: "Brazil",
    status: "proposed",
    category: "legislation",
    summary: "Brazil's comprehensive AI regulation bill modeled partly on the EU AI Act. Passed the Senate in December 2024, pending review in the Chamber of Deputies. Establishes risk-based classification and designates ANPD as primary AI regulatory body.",
    key_requirements: [
      "Risk-based classification system for AI systems (excessive, high, and general risk)",
      "Prohibition of social scoring and subliminal manipulation AI systems",
      "Impact assessments mandatory for high-risk AI systems",
      "Right to human review of automated decisions",
      "Transparency requirements including disclosure of AI system use",
    ],
    compliance_implications: [
      "If enacted, fines up to R$50 million or 2% of company revenue per violation",
      "Extraterritorial scope: applies to AI systems producing effects in Brazil",
    ],
    effective_date: null,
    source_url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/163592",
    source_name: "Brazilian Federal Senate",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Illinois AI Video Interview Act (AIVI) and Biometric Information Privacy Act (BIPA)",
    jurisdiction: "US-IL",
    jurisdiction_display: "United States — Illinois",
    status: "in_effect",
    category: "legislation",
    summary: "Two Illinois laws with significant AI implications. AIVI regulates AI-driven video interview analysis. BIPA is the strictest biometric privacy law in the US, requiring informed consent before collecting biometric identifiers. Combined, they create substantial compliance requirements.",
    key_requirements: [
      "AIVI: Employers must notify applicants that AI will analyze their video interview",
      "AIVI: Written consent required before AI analysis of video interviews",
      "BIPA: Written informed consent required before collecting biometric identifiers",
      "BIPA: Organizations must publish a biometric data retention and destruction policy",
      "BIPA: Private right of action — individuals can sue directly for violations",
    ],
    compliance_implications: [
      "BIPA: $1,000 (negligent) to $5,000 (intentional) per violation",
      "Class action settlements under BIPA have reached hundreds of millions (Facebook $650M, Google $100M)",
      "Private right of action makes Illinois the highest-risk US jurisdiction for biometric AI",
    ],
    effective_date: "2020-01-01",
    source_url: "https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3004&ChapterID=57",
    source_name: "Illinois General Assembly",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Indonesia Personal Data Protection Law (UU PDP, Law No. 27 of 2022)",
    jurisdiction: "ID",
    jurisdiction_display: "Indonesia",
    status: "in_effect",
    category: "legislation",
    summary: "Indonesia's comprehensive data protection law, fully effective October 17, 2024. Modeled on GDPR with unique criminal penalties. Governs AI systems processing personal data of Indonesian residents.",
    key_requirements: [
      "Lawful basis required for all personal data processing",
      "Data subjects have rights to access, correct, delete, restrict, and portability",
      "Data breach notification to authorities within 72 hours",
      "Data Protection Impact Assessments required for high-risk processing",
      "Specific consent required for processing sensitive personal data",
    ],
    compliance_implications: [
      "Administrative fines up to 2% of annual revenue for corporate violations",
      "Criminal sanctions: imprisonment 4-6 years and fines up to IDR 6 billion",
      "Extraterritorial scope: applies to any entity processing data of Indonesian residents",
    ],
    effective_date: "2024-10-17",
    source_url: "https://peraturan.bpk.go.id/Details/229798/uu-no-27-tahun-2022",
    source_name: "Indonesian Law Repository (JDIH BPK)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "California AI Transparency Act (SB 942) and AI Watermarking Requirements (AB 853)",
    jurisdiction: "US-CA",
    jurisdiction_display: "United States — California",
    status: "enacted",
    category: "legislation",
    summary: "California's AI transparency legislation requiring developers of generative AI systems to provide content detection tools and make provenance data available. Effective date delayed to August 2, 2026 by AB 853.",
    key_requirements: [
      "Developers of generative AI must provide free AI content detection tools",
      "AI-generated content must include provenance data (metadata or watermarks)",
      "Detection tools must be publicly accessible and free of charge",
      "Annual reporting on AI detection tool performance and accessibility",
    ],
    compliance_implications: [
      "Effective August 2, 2026 (delayed from January 1, 2026)",
      "Applies to generative AI systems with over 1 million monthly users/interactions",
      "Enforced by the California Attorney General — civil penalties per violation",
    ],
    effective_date: "2026-08-02",
    source_url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB942",
    source_name: "California Legislative Information",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "OECD Principles on Artificial Intelligence",
    jurisdiction: "INTL",
    jurisdiction_display: "International (OECD — 46 countries)",
    status: "in_effect",
    category: "standard",
    summary: "First intergovernmental standard on AI adopted May 2019, updated May 2024. Endorsed by 46 OECD member and partner countries. Non-binding but forms the foundation referenced by most national AI regulations globally.",
    key_requirements: [
      "Inclusive growth, sustainable development, and well-being",
      "Human-centred values and fairness: respect human rights and enable oversight",
      "Transparency and explainability of AI system outputs and processes",
      "Robustness, security, and safety: AI must not pose unreasonable risks",
      "Accountability: organizations are accountable for proper AI functioning",
    ],
    compliance_implications: [
      "Non-binding but widely referenced in national legislation",
      "Referenced in EU AI Act, Brazil AI Bill, and NIST AI RMF preambles",
    ],
    effective_date: "2019-05-22",
    source_url: "https://oecd.ai/en/ai-principles",
    source_name: "OECD AI Policy Observatory",
    ai_classified: false,
    ai_confidence: null,
  },
  // New US state AI legislation
  {
    title: "Connecticut AI Act (SB 2, Public Act 24-148)",
    jurisdiction: "US-CT",
    jurisdiction_display: "United States — Connecticut",
    status: "enacted",
    category: "legislation",
    summary: "Connecticut's AI accountability law requiring deployers of high-risk AI systems to conduct impact assessments and provide notice to consumers. Applies to AI systems making consequential decisions in employment, education, financial services, healthcare, housing, and insurance.",
    key_requirements: [
      "Impact assessments required for high-risk AI systems before and during deployment",
      "Consumers must be notified when AI makes a consequential decision about them",
      "Right to explanation of AI-driven decisions affecting consumers",
      "Developers must provide documentation on training data and known limitations",
      "Annual review and update of impact assessments",
    ],
    compliance_implications: [
      "Enforced by Connecticut Attorney General",
      "Effective February 1, 2026",
      "Affirmative defense for compliance with NIST AI RMF or ISO/IEC 42001",
    ],
    effective_date: "2026-02-01",
    source_url: "https://www.cga.ct.gov/asp/cgabillstatus/cgabillstatus.asp?selBillType=Bill&bill_num=SB2&which_year=2024",
    source_name: "Connecticut General Assembly",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Utah Artificial Intelligence Policy Act (SB 149)",
    jurisdiction: "US-UT",
    jurisdiction_display: "United States — Utah",
    status: "in_effect",
    category: "legislation",
    summary: "Utah's AI disclosure law requiring businesses to clearly disclose when consumers are interacting with generative AI. Creates the Office of AI Policy within the Department of Commerce. First US state AI law to take effect (May 1, 2024).",
    key_requirements: [
      "Businesses must disclose to consumers when they are interacting with generative AI",
      "Creates Office of AI Policy for ongoing regulatory oversight",
      "Establishes AI Learning Laboratory Program for regulatory sandboxes",
      "Requires disclosure when AI-generated content is used in regulated industries",
    ],
    compliance_implications: [
      "Enforced under existing consumer protection laws by Utah AG",
      "Relatively narrow scope focused on disclosure rather than comprehensive governance",
      "First US state AI law to take effect — establishes precedent",
    ],
    effective_date: "2024-05-01",
    source_url: "https://le.utah.gov/~2024/bills/static/SB0149.html",
    source_name: "Utah State Legislature",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Tennessee ELVIS Act (Ensuring Likeness Voice and Image Security Act)",
    jurisdiction: "US-TN",
    jurisdiction_display: "United States — Tennessee",
    status: "in_effect",
    category: "legislation",
    summary: "Tennessee's law protecting individuals against unauthorized AI-generated deepfakes of their voice and likeness. Extends the state's existing right of publicity to cover AI-generated replicas. Named in reference to Elvis Presley and Nashville's music industry.",
    key_requirements: [
      "Prohibits use of AI to generate a person's voice or likeness without consent",
      "Applies to both commercial and non-commercial uses of AI-generated replicas",
      "Requires consent from the individual (or estate) before AI replication of voice/image",
      "Private right of action for individuals whose likeness is misused by AI",
    ],
    compliance_implications: [
      "Statutory damages available plus actual damages and attorney fees",
      "Applies to AI systems generating synthetic voice, images, or video",
      "Particularly relevant for music, entertainment, and content generation AI",
    ],
    effective_date: "2024-07-01",
    source_url: "https://www.capitol.tn.gov/Bills/113/Bill/HB2091.pdf",
    source_name: "Tennessee General Assembly",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "New York City Local Law 144 — Automated Employment Decision Tools (AEDT)",
    jurisdiction: "US-NYC",
    jurisdiction_display: "United States — New York City",
    status: "in_effect",
    category: "legislation",
    summary: "NYC's law requiring employers using AI-based automated employment decision tools to conduct annual bias audits and provide notice to candidates. First US local law specifically regulating AI in hiring.",
    key_requirements: [
      "Annual independent bias audit required for automated employment decision tools",
      "Summary of bias audit results must be publicly posted on employer's website",
      "Candidates must be notified at least 10 business days before AEDT is used",
      "Notice must describe the job qualifications and characteristics the AEDT evaluates",
      "Candidates can request alternative selection process or accommodation",
    ],
    compliance_implications: [
      "Penalties: $500 for first violation, $500-$1,500 per subsequent violation per day",
      "Enforced by NYC Department of Consumer and Worker Protection",
      "Applies to employers and employment agencies in New York City",
    ],
    effective_date: "2023-07-05",
    source_url: "https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page",
    source_name: "NYC Department of Consumer and Worker Protection",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "South Korea AI Basic Act (AI Industry Promotion and Trust Framework Act)",
    jurisdiction: "KR",
    jurisdiction_display: "South Korea",
    status: "enacted",
    category: "legislation",
    summary: "South Korea's comprehensive AI framework law passed by the National Assembly in December 2024. Establishes an AI Committee under the Prime Minister, defines high-impact AI, and creates notification and transparency requirements. Takes effect January 2026.",
    key_requirements: [
      "AI Committee established under the Prime Minister for national AI strategy",
      "High-impact AI systems defined and subject to enhanced obligations",
      "Transparency obligations for AI systems interacting with users",
      "Impact assessments required for high-impact AI in public sector",
      "AI development must respect human rights and democratic values",
    ],
    compliance_implications: [
      "Penalties to be determined by implementing regulations",
      "Creates foundation for sector-specific AI regulation in South Korea",
      "Applies to AI systems deployed in or targeting South Korean market",
    ],
    effective_date: "2026-01-22",
    source_url: "https://www.law.go.kr",
    source_name: "Korea Ministry of Government Legislation",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Japan AI Guidelines for Business (METI)",
    jurisdiction: "JP",
    jurisdiction_display: "Japan",
    status: "in_effect",
    category: "guidance",
    summary: "Japan's principles-based approach to AI governance issued by METI (Ministry of Economy, Trade and Industry). Emphasizes 'agile governance' and industry self-regulation. Updated in 2024 to address generative AI and foundation models.",
    key_requirements: [
      "Human-centric AI development that respects dignity and autonomy",
      "Transparency and explainability of AI systems proportional to risk",
      "Safety and security measures including testing and monitoring",
      "Fair competition and consumer protection in AI markets",
      "Privacy protection and appropriate data handling in AI systems",
    ],
    compliance_implications: [
      "Voluntary guidelines — no direct penalties",
      "Compliance expected for government procurement and trusted AI certifications",
      "Japan pursuing 'agile governance' rather than comprehensive AI legislation",
    ],
    effective_date: "2024-04-19",
    source_url: "https://www.meti.go.jp/english/policy/economy/ai_governance/index.html",
    source_name: "Ministry of Economy, Trade and Industry (METI)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "China Interim Measures for the Management of Generative AI Services",
    jurisdiction: "CN",
    jurisdiction_display: "China",
    status: "in_effect",
    category: "legislation",
    summary: "China's regulation governing generative AI services, effective August 15, 2023. Requires providers to ensure generated content adheres to socialist core values, does not contain illegal content, and is properly labeled. Providers must register algorithms with the Cyberspace Administration of China.",
    key_requirements: [
      "Training data must be lawfully obtained and not infringe intellectual property",
      "Generated content must not subvert state power or undermine national unity",
      "AI-generated content must be labeled as such",
      "Algorithm registration with the Cyberspace Administration of China required",
      "User real-name verification and complaint mechanisms required",
      "Security assessments required before public deployment",
    ],
    compliance_implications: [
      "Penalties under existing cybersecurity and data protection laws",
      "Services may be suspended or shut down for serious violations",
      "Applies to generative AI services provided to users within China",
    ],
    effective_date: "2023-08-15",
    source_url: "http://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm",
    source_name: "Cyberspace Administration of China",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Australia AI Ethics Framework and Proposed Mandatory Guardrails",
    jurisdiction: "AU",
    jurisdiction_display: "Australia",
    status: "under_review",
    category: "framework",
    summary: "Australia's voluntary AI Ethics Framework (2019) plus proposed mandatory guardrails announced in 2024. The government is consulting on mandatory obligations for high-risk AI including transparency, testing, and accountability. Legislation expected 2025-2026.",
    key_requirements: [
      "Eight AI ethics principles: human wellbeing, fairness, privacy, reliability, transparency, contestability, accountability, human oversight",
      "Proposed mandatory guardrails for high-risk AI applications",
      "Transparency obligations for AI systems making decisions about individuals",
      "Mandatory testing and monitoring for high-risk AI deployments",
    ],
    compliance_implications: [
      "Current framework is voluntary — mandatory requirements pending",
      "Government consulting on penalty structures for mandatory guardrails",
      "Applies to AI systems deployed in Australia or affecting Australian residents",
    ],
    effective_date: null,
    source_url: "https://www.industry.gov.au/publications/australias-artificial-intelligence-ethics-framework",
    source_name: "Australian Department of Industry, Science and Resources",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "India Digital Personal Data Protection Act (DPDPA, 2023)",
    jurisdiction: "IN",
    jurisdiction_display: "India",
    status: "enacted",
    category: "legislation",
    summary: "India's data protection law enacted August 2023, with implementing rules pending. Governs the processing of digital personal data by AI systems. Establishes the Data Protection Board of India for enforcement. Significant implications for AI systems processing Indian citizens' data.",
    key_requirements: [
      "Consent required for processing personal data (with exemptions for legitimate uses)",
      "Data fiduciaries must implement reasonable security safeguards",
      "Right to correction and erasure of personal data",
      "Data Protection Board of India for adjudication and enforcement",
      "Cross-border data transfer restrictions to be specified by government",
      "Significant data fiduciaries face additional obligations including DPO appointment and audits",
    ],
    compliance_implications: [
      "Penalties up to INR 250 crore (~$30M) per violation",
      "Applies to processing of digital personal data within India and overseas processing targeting Indian users",
      "Implementing rules still pending — full enforcement timeline uncertain",
    ],
    effective_date: "2023-08-11",
    source_url: "https://www.meity.gov.in/data-protection-framework",
    source_name: "Ministry of Electronics and Information Technology (MeitY)",
    ai_classified: false,
    ai_confidence: null,
  },
  // ================================================================
  // B. DATA PROTECTION LAWS WITH AI PROVISIONS
  // ================================================================
  {
    title: "EU General Data Protection Regulation (GDPR) — AI Provisions",
    jurisdiction: "EU",
    jurisdiction_display: "European Union",
    status: "in_effect",
    category: "legislation",
    summary: "The GDPR's provisions specifically relevant to AI: Article 22 (automated individual decision-making), data protection impact assessments for AI, and the right to explanation. Foundational regulation that intersects with the EU AI Act.",
    key_requirements: [
      "Art. 22: Right not to be subject to solely automated decisions with legal/significant effects",
      "Data Protection Impact Assessments required for systematic profiling and automated decision-making",
      "Right to meaningful information about the logic involved in automated decisions",
      "Data minimization: only process data necessary for the AI system's purpose",
      "Purpose limitation: data collected for one purpose cannot be repurposed for AI training without consent",
    ],
    compliance_implications: [
      "Fines up to €20M or 4% of global annual turnover",
      "AI systems making automated decisions must provide opt-out and human review",
      "Supervisory authorities across EU member states enforce locally",
    ],
    effective_date: "2018-05-25",
    source_url: "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
    source_name: "Official Journal of the European Union",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "California Consumer Privacy Act / California Privacy Rights Act (CCPA/CPRA) — AI Provisions",
    jurisdiction: "US-CA",
    jurisdiction_display: "United States — California",
    status: "in_effect",
    category: "legislation",
    summary: "California's comprehensive privacy law with specific provisions for automated decision-making and profiling. CPRA (2023 amendments) added rights related to AI-driven profiling and automated decisions, enforced by the California Privacy Protection Agency.",
    key_requirements: [
      "Right to opt-out of automated decision-making technology",
      "Right to know about profiling and automated decision-making logic",
      "Businesses must conduct risk assessments for AI processing of personal data",
      "Consumers can request information about automated decision outcomes",
      "CPPA rulemaking on automated decision-making technology ongoing",
    ],
    compliance_implications: [
      "Civil penalties: $2,500 per violation, $7,500 per intentional violation",
      "Private right of action for data breaches",
      "Enforced by California Privacy Protection Agency and California AG",
    ],
    effective_date: "2023-01-01",
    source_url: "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?division=3.&part=4.&lawCode=CIV&title=1.81.5",
    source_name: "California Legislative Information",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Brazil General Data Protection Law (LGPD, Lei 13.709/2018)",
    jurisdiction: "BR",
    jurisdiction_display: "Brazil",
    status: "in_effect",
    category: "legislation",
    summary: "Brazil's comprehensive data protection law modeled on GDPR. Contains specific provisions for automated decision-making including the right to review and explanation of AI-driven decisions. Enforced by the ANPD.",
    key_requirements: [
      "Legal basis required for all personal data processing including by AI systems",
      "Right to review of decisions made solely by automated processing",
      "Right to clear and adequate information about the criteria and procedures used in automated decisions",
      "Data Protection Impact Assessments for high-risk AI processing",
      "Data minimization and purpose limitation apply to AI training data",
    ],
    compliance_implications: [
      "Fines up to 2% of revenue in Brazil, capped at R$50 million per violation",
      "ANPD actively investigating AI data processing practices",
      "Applies to any processing of personal data of individuals located in Brazil",
    ],
    effective_date: "2020-09-18",
    source_url: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm",
    source_name: "Presidency of the Republic of Brazil",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "South Africa Protection of Personal Information Act (POPIA) — AI Provisions",
    jurisdiction: "ZA",
    jurisdiction_display: "South Africa",
    status: "in_effect",
    category: "legislation",
    summary: "South Africa's data protection law with specific provisions for automated decision-making. Section 71 gives data subjects the right not to be subject to decisions based solely on automated processing, including AI profiling.",
    key_requirements: [
      "Section 71: Right not to be subject to decisions based solely on automated processing",
      "Data subjects must be notified of automated decision-making",
      "Appropriate safeguards required for automated processing of personal information",
      "Right to submit representations against automated decisions",
      "Prior authorisation from Information Regulator for certain processing activities",
    ],
    compliance_implications: [
      "Fines up to ZAR 10 million and/or imprisonment up to 10 years",
      "Enforced by the Information Regulator",
      "Applies to processing of personal information within South Africa",
    ],
    effective_date: "2021-07-01",
    source_url: "https://www.gov.za/documents/protection-personal-information-act",
    source_name: "Government of South Africa",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Japan Act on Protection of Personal Information (APPI) — AI Amendments",
    jurisdiction: "JP",
    jurisdiction_display: "Japan",
    status: "in_effect",
    category: "legislation",
    summary: "Japan's data protection law, most recently amended in 2022, with provisions affecting AI systems. Requires purpose specification for personal data processing, consent for AI-driven profiling, and restricts cross-border data transfers used for AI training.",
    key_requirements: [
      "Purpose of personal data use must be specified as clearly as possible",
      "Consent required for use of personal data beyond specified purposes",
      "Restrictions on provision of personal data to third parties including AI processors",
      "Cross-border transfer rules affect AI training data flows",
      "Individual rights to access, correct, and delete personal data processed by AI",
    ],
    compliance_implications: [
      "Criminal penalties: imprisonment up to 1 year or fine up to JPY 1 million for individuals",
      "Corporate fines up to JPY 100 million for certain violations",
      "Enforced by Personal Information Protection Commission (PPC)",
    ],
    effective_date: "2022-04-01",
    source_url: "https://www.ppc.go.jp/en/legal/",
    source_name: "Personal Information Protection Commission (PPC)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Saudi Arabia Personal Data Protection Law (PDPL)",
    jurisdiction: "SA",
    jurisdiction_display: "Saudi Arabia",
    status: "in_effect",
    category: "legislation",
    summary: "Saudi Arabia's comprehensive personal data protection law, effective September 2023 with a compliance deadline of September 2024. Contains provisions for automated decision-making and AI processing of personal data.",
    key_requirements: [
      "Legal basis required for processing personal data",
      "Data subjects must be informed when automated decision-making is used",
      "Right to object to automated decisions with significant effects",
      "Data Protection Impact Assessments for high-risk processing",
      "Consent required for processing sensitive personal data",
    ],
    compliance_implications: [
      "Fines up to SAR 5 million (~$1.3M) for violations",
      "Criminal penalties including imprisonment for certain violations",
      "Enforced by Saudi Data and AI Authority (SDAIA)",
    ],
    effective_date: "2023-09-14",
    source_url: "https://sdaia.gov.sa/en/SDAIA/about/Documents/Personal%20Data%20English%20V2-23April2023-%20Reviewed-.pdf",
    source_name: "Saudi Data and AI Authority (SDAIA)",
    ai_classified: false,
    ai_confidence: null,
  },
  // ================================================================
  // C. FINANCIAL SERVICES AI REGULATIONS
  // ================================================================
  {
    title: "EU Digital Operational Resilience Act (DORA)",
    jurisdiction: "EU",
    jurisdiction_display: "European Union",
    status: "in_effect",
    category: "legislation",
    summary: "EU regulation establishing ICT risk management requirements for financial institutions, including AI/ML systems used in financial services. Requires testing, incident reporting, and third-party risk management for AI in finance.",
    key_requirements: [
      "ICT risk management framework must cover AI/ML systems",
      "Digital operational resilience testing including AI models",
      "ICT incident reporting for AI system failures affecting financial services",
      "Third-party risk management for AI/cloud service providers",
      "Information sharing on AI-related cyber threats",
    ],
    compliance_implications: [
      "Penalties determined by national competent authorities, up to 1% of average daily worldwide turnover",
      "Applies to banks, insurance, investment firms, and other financial entities using AI",
      "Effective January 17, 2025",
    ],
    effective_date: "2025-01-17",
    source_url: "https://eur-lex.europa.eu/eli/reg/2022/2554/oj",
    source_name: "Official Journal of the European Union",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "US OCC Model Risk Management Guidance (SR 11-7 / OCC 2011-12)",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "guidance",
    summary: "Federal banking regulators' guidance on model risk management, widely applied to AI/ML models in banking. Requires validation, monitoring, and governance of all quantitative models including AI/ML systems used for credit, risk, and compliance.",
    key_requirements: [
      "Model development must follow sound practices with documented methodologies",
      "Independent model validation required before deployment",
      "Ongoing monitoring of model performance and limitations",
      "Model inventory and governance framework required",
      "Board and senior management oversight of model risk",
    ],
    compliance_implications: [
      "Supervisory action (MRA/MRIA) for non-compliance during bank examinations",
      "No direct fines but impacts bank ratings and can trigger enforcement actions",
      "Applies to all OCC-supervised banks and federal savings associations",
    ],
    effective_date: "2011-04-04",
    source_url: "https://www.occ.gov/news-issuances/bulletins/2011/bulletin-2011-12.html",
    source_name: "Office of the Comptroller of the Currency (OCC)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Singapore MAS Guidelines on AI in Financial Services (FEAT Principles)",
    jurisdiction: "SG",
    jurisdiction_display: "Singapore",
    status: "in_effect",
    category: "guidance",
    summary: "Monetary Authority of Singapore's FEAT principles (Fairness, Ethics, Accountability, Transparency) for AI use in financial services. Provides practical guidance on governance, risk management, and responsible use of AI/ML in banking, insurance, and capital markets.",
    key_requirements: [
      "Fairness: AI systems must not systematically disadvantage specific groups",
      "Ethics: AI use in finance must align with ethical standards and firm values",
      "Accountability: Clear roles and responsibilities for AI governance",
      "Transparency: AI decisions in finance must be explainable to customers and regulators",
      "Regular review and testing of AI models for bias and accuracy",
    ],
    compliance_implications: [
      "Voluntary principles but referenced in MAS supervisory expectations",
      "Non-compliance may result in supervisory actions during MAS inspections",
      "Applies to all MAS-regulated financial institutions",
    ],
    effective_date: "2022-05-01",
    source_url: "https://www.mas.gov.sg/publications/monographs-or-information-paper/2018/feat",
    source_name: "Monetary Authority of Singapore (MAS)",
    ai_classified: false,
    ai_confidence: null,
  },
  // ================================================================
  // D. HEALTHCARE AI
  // ================================================================
  {
    title: "FDA AI/ML-Based Software as Medical Device (SaMD) Framework",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "framework",
    summary: "FDA's regulatory framework for AI/ML-based software as a medical device. Establishes a total product lifecycle approach allowing predetermined changes to AI algorithms without requiring new premarket submissions, while maintaining safety and effectiveness.",
    key_requirements: [
      "Premarket review (510(k), De Novo, PMA) required for AI/ML-based SaMD",
      "Good Machine Learning Practice (GMLP) principles for development",
      "Predetermined change control plan for AI algorithm modifications",
      "Real-world performance monitoring and post-market surveillance",
      "Labeling requirements specific to AI/ML-based SaMD capabilities and limitations",
    ],
    compliance_implications: [
      "FDA enforcement actions for unapproved AI medical devices",
      "Warning letters, recalls, and injunctions for non-compliant AI devices",
      "Applies to AI software that diagnoses, treats, or prevents disease",
    ],
    effective_date: "2021-01-01",
    source_url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-software-medical-device",
    source_name: "U.S. Food and Drug Administration (FDA)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "WHO Guidance on Ethics and Governance of AI for Health",
    jurisdiction: "INTL",
    jurisdiction_display: "International (WHO)",
    status: "in_effect",
    category: "guidance",
    summary: "World Health Organization's guidance on ethical use of AI in healthcare, published June 2021. Establishes six core principles and provides recommendations for governments, developers, and healthcare providers on responsible AI deployment in health systems.",
    key_requirements: [
      "Protect human autonomy in AI-assisted healthcare decisions",
      "Promote human well-being and safety as primary objectives",
      "Ensure transparency and explainability of health AI systems",
      "Foster accountability for AI outcomes in healthcare",
      "Ensure inclusiveness and equity in AI health applications",
      "Promote responsive and sustainable AI development for health",
    ],
    compliance_implications: [
      "Non-binding guidance but influential in national health AI policy",
      "Referenced by multiple national regulators in their health AI frameworks",
      "Applies to all AI systems used in health and healthcare contexts",
    ],
    effective_date: "2021-06-28",
    source_url: "https://www.who.int/publications/i/item/9789240029200",
    source_name: "World Health Organization (WHO)",
    ai_classified: false,
    ai_confidence: null,
  },
  // ================================================================
  // E. EMPLOYMENT / HR AI
  // ================================================================
  {
    title: "Maryland Facial Recognition in Hiring (HB 1202)",
    jurisdiction: "US-MD",
    jurisdiction_display: "United States — Maryland",
    status: "in_effect",
    category: "legislation",
    summary: "Maryland's law prohibiting employers from using facial recognition technology during job applicant interviews without the applicant's prior written consent. One of the first US state laws specifically addressing facial recognition AI in employment.",
    key_requirements: [
      "Employers may not use facial recognition during applicant interviews without consent",
      "Applicant must provide written consent (not merely implied by interview participation)",
      "Waiver of rights under this law is void and unenforceable",
    ],
    compliance_implications: [
      "Enforced by Maryland Attorney General under consumer protection authority",
      "Relatively narrow scope — only covers facial recognition in interviews",
      "Applies to any employer conducting interviews in Maryland",
    ],
    effective_date: "2020-10-01",
    source_url: "https://mgaleg.maryland.gov/mgawebsite/Legislation/Details/HB1202?ys=2020RS",
    source_name: "Maryland General Assembly",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "EU Platform Workers Directive — Algorithmic Management",
    jurisdiction: "EU",
    jurisdiction_display: "European Union",
    status: "enacted",
    category: "legislation",
    summary: "EU directive regulating the use of algorithmic management by digital labor platforms. Restricts automated decision-making in employment relationships, requires human oversight of AI-driven work allocation, performance monitoring, and disciplinary actions.",
    key_requirements: [
      "Platforms must disclose use of automated monitoring and decision-making systems",
      "Human oversight required for significant automated decisions affecting workers",
      "Workers have right to explanation of automated decisions",
      "Restriction on processing certain categories of worker personal data by algorithms",
      "Regular review of automated systems' impact on working conditions",
    ],
    compliance_implications: [
      "Member states must transpose into national law by December 2026",
      "Penalties determined by national implementation",
      "Applies to digital labor platforms operating in the EU",
    ],
    effective_date: "2026-12-01",
    source_url: "https://eur-lex.europa.eu/eli/dir/2024/2831/oj",
    source_name: "Official Journal of the European Union",
    ai_classified: false,
    ai_confidence: null,
  },
  // ================================================================
  // F. INTERNATIONAL FRAMEWORKS AND STANDARDS
  // ================================================================
  {
    title: "UNESCO Recommendation on the Ethics of Artificial Intelligence",
    jurisdiction: "INTL",
    jurisdiction_display: "International (UNESCO — 193 members)",
    status: "in_effect",
    category: "standard",
    summary: "First global normative instrument on AI ethics, adopted November 2021 by all 193 UNESCO member states. Covers values, principles, and policy areas for ethical AI. Non-binding but provides a global ethical baseline referenced by national AI strategies.",
    key_requirements: [
      "Proportionality: AI must be appropriate and limited to what is necessary",
      "Safety and security: unwanted harms must be prevented",
      "Right to privacy and data protection in AI systems",
      "Transparency and explainability of AI processes",
      "Human oversight and determination of AI systems",
      "Environmental sustainability of AI development and deployment",
    ],
    compliance_implications: [
      "Non-binding recommendation adopted by all 193 UN member states",
      "Referenced in national AI strategies and legislation globally",
      "UNESCO conducting readiness assessments for implementation",
    ],
    effective_date: "2021-11-23",
    source_url: "https://unesdoc.unesco.org/ark:/48223/pf0000381137",
    source_name: "UNESCO",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "Council of Europe Framework Convention on AI, Human Rights, Democracy and Rule of Law",
    jurisdiction: "INTL",
    jurisdiction_display: "International (Council of Europe)",
    status: "enacted",
    category: "standard",
    summary: "First legally binding international treaty on AI, opened for signature September 5, 2024. Covers AI systems across public and private sectors with obligations to protect human rights, democracy, and rule of law. Open to non-Council of Europe members including US, Japan, Australia.",
    key_requirements: [
      "AI systems must respect human rights, democracy, and rule of law",
      "Transparency requirements for AI systems affecting individuals",
      "Accountability and remedies for AI-related harms",
      "Risk assessment and mitigation for AI systems",
      "Protection of equality and non-discrimination in AI",
      "Privacy and personal data protection in AI systems",
    ],
    compliance_implications: [
      "Legally binding treaty — signatory states must implement in national law",
      "Compliance monitored by Conference of Parties",
      "Open to non-European states — US, Japan, Australia among signatories",
    ],
    effective_date: "2024-09-05",
    source_url: "https://www.coe.int/en/web/artificial-intelligence/the-framework-convention-on-artificial-intelligence",
    source_name: "Council of Europe",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "ISO/IEC 42001:2023 — AI Management System Standard",
    jurisdiction: "INTL",
    jurisdiction_display: "International (ISO/IEC)",
    status: "in_effect",
    category: "standard",
    summary: "First international management system standard for AI, published December 2023. Provides requirements for establishing, implementing, maintaining, and improving an AI management system within organizations. Certifiable standard similar to ISO 27001 for information security.",
    key_requirements: [
      "Establish an AI management system with defined scope, policies, and objectives",
      "AI risk assessment and treatment process for all AI systems",
      "Organizational roles and responsibilities for AI governance",
      "Competence requirements for personnel involved in AI lifecycle",
      "Monitoring, measurement, analysis, and evaluation of AI system performance",
      "Continual improvement of the AI management system",
    ],
    compliance_implications: [
      "Certifiable standard — third-party audits available",
      "Referenced as recognized framework in Colorado AI Act and Connecticut AI Act",
      "Increasingly required in enterprise procurement and government contracts",
    ],
    effective_date: "2023-12-18",
    source_url: "https://www.iso.org/standard/81230.html",
    source_name: "International Organization for Standardization (ISO)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "NIST AI 600-1: Generative AI Profile",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "framework",
    summary: "NIST's companion publication to the AI RMF specifically addressing risks of generative AI. Maps generative AI-specific risks to the AI RMF's Govern, Map, Measure, and Manage functions. Published July 2024.",
    key_requirements: [
      "Identifies 12 generative AI-specific risk categories (CBRN, confabulation, data privacy, etc.)",
      "Maps risks to AI RMF subcategories with suggested actions",
      "Guidance on provenance tracking for AI-generated content",
      "Content authentication and watermarking recommendations",
      "Human-AI interaction considerations for generative systems",
    ],
    compliance_implications: [
      "Voluntary companion to AI RMF — strengthens safe harbor claims",
      "Referenced by regulators evaluating generative AI compliance",
      "Provides specific technical guidance for genAI deployments",
    ],
    effective_date: "2024-07-26",
    source_url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence",
    source_name: "National Institute of Standards and Technology",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "G7 Hiroshima AI Process International Code of Conduct",
    jurisdiction: "INTL",
    jurisdiction_display: "International (G7)",
    status: "in_effect",
    category: "standard",
    summary: "Voluntary code of conduct for advanced AI systems agreed by G7 leaders in October 2023. Provides 11 guiding principles for organizations developing and deploying advanced AI systems including foundation models and generative AI.",
    key_requirements: [
      "Take appropriate measures to identify, evaluate, and mitigate risks across the AI lifecycle",
      "Identify and mitigate vulnerabilities, incidents, and misuse patterns after deployment",
      "Publicly report advanced AI systems' capabilities, limitations, and domains of use",
      "Invest in responsible information sharing and incident reporting",
      "Develop and implement AI watermarking and provenance mechanisms",
    ],
    compliance_implications: [
      "Voluntary code — no enforcement mechanism",
      "Signaled by G7 as baseline expectations for AI developers",
      "May influence future regulatory requirements in G7 member states",
    ],
    effective_date: "2023-10-30",
    source_url: "https://www.mofa.go.jp/ecm/ec/page5e_000076.html",
    source_name: "Ministry of Foreign Affairs of Japan (G7 Presidency)",
    ai_classified: false,
    ai_confidence: null,
  },
  // ================================================================
  // G. SECTOR-SPECIFIC
  // ================================================================
  {
    title: "FTC Enforcement Actions on AI — Section 5 Authority",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "guidance",
    summary: "The FTC's use of Section 5 of the FTC Act to pursue enforcement actions against deceptive and unfair AI practices. Covers false AI claims, biased algorithms, dark patterns in AI, and unauthorized collection of data for AI training. Multiple enforcement actions since 2021.",
    key_requirements: [
      "AI claims must be truthful and substantiated (no 'AI washing')",
      "AI systems must not be unfair or deceptive under Section 5",
      "Companies must not use dark patterns to extract data for AI training",
      "Algorithmic bias constitutes an unfair practice when it causes consumer harm",
      "Health AI claims subject to heightened scrutiny",
    ],
    compliance_implications: [
      "FTC can require algorithmic disgorgement (deletion of AI models trained on improperly obtained data)",
      "Civil penalties up to $50,120 per violation (2024 adjusted amount)",
      "Consent decrees with ongoing monitoring requirements",
    ],
    effective_date: "2021-04-01",
    source_url: "https://www.ftc.gov/business-guidance/blog/2023/02/keep-your-ai-claims-check",
    source_name: "Federal Trade Commission (FTC)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "EEOC Guidance on AI in Employment Decisions",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "guidance",
    summary: "EEOC's technical assistance guidance on how employers' use of AI and automated systems can violate Title VII, the ADA, and other federal anti-discrimination laws. Covers disparate impact analysis for AI hiring tools and reasonable accommodation in AI assessments.",
    key_requirements: [
      "AI hiring tools must not cause disparate impact on protected groups",
      "Employers are liable for discriminatory AI outcomes even if using third-party tools",
      "AI assessments must provide reasonable accommodations for disabilities (ADA)",
      "Selection rates must be analyzed under the four-fifths rule for AI tools",
      "Employers should audit AI hiring tools for bias before and during use",
    ],
    compliance_implications: [
      "Title VII and ADA enforcement applies to AI-driven employment decisions",
      "Employers cannot deflect liability to AI vendors",
      "EEOC has initiated enforcement actions against AI hiring discrimination",
    ],
    effective_date: "2023-05-18",
    source_url: "https://www.eeoc.gov/newsroom/eeoc-launches-initiative-artificial-intelligence-and-algorithmic-fairness",
    source_name: "Equal Employment Opportunity Commission (EEOC)",
    ai_classified: false,
    ai_confidence: null,
  },
  {
    title: "CFPB Guidance on AI in Consumer Finance",
    jurisdiction: "US",
    jurisdiction_display: "United States (Federal)",
    status: "in_effect",
    category: "guidance",
    summary: "Consumer Financial Protection Bureau's guidance on use of AI in consumer financial products. Addresses chatbots in customer service, AI credit underwriting, adverse action notice requirements, and fair lending obligations for AI-driven financial decisions.",
    key_requirements: [
      "AI-driven adverse credit decisions must provide specific reasons to consumers (not generic 'algorithm' explanations)",
      "AI chatbots must not impede consumers from reaching human representatives",
      "Fair lending laws (ECOA) apply fully to AI-driven lending decisions",
      "AI marketing and targeting must not facilitate discriminatory lending practices",
      "Consumer complaint data must be analyzed for AI-related harms",
    ],
    compliance_implications: [
      "CFPB can impose civil penalties and require remediation for AI-related violations",
      "ECOA violations in AI lending can result in significant enforcement actions",
      "Applies to all CFPB-supervised financial institutions using AI",
    ],
    effective_date: "2023-09-19",
    source_url: "https://www.consumerfinance.gov/data-research/research-reports/chatbots-in-consumer-finance/chatbots-in-consumer-finance/",
    source_name: "Consumer Financial Protection Bureau (CFPB)",
    ai_classified: false,
    ai_confidence: null,
  },
];

// ================================================================
// SEED UPDATES
// ================================================================

export const seedUpdates = [
  { regulation_index: 0, update_type: "status_change" as const, title: "EU AI Act Enters Full Application Phase", summary: "Core provisions of the EU AI Act become fully applicable on August 2, 2026. High-risk AI systems must now comply with conformity assessment requirements.", source_url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj", verified: true, verified_by: "Manual verification" },
  { regulation_index: 1, update_type: "new_regulation" as const, title: "Texas TRAIGA Takes Effect January 1, 2026", summary: "The Texas Responsible AI Governance Act took effect on January 1, 2026, making Texas one of the first US states with comprehensive AI governance legislation.", source_url: "https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB149", verified: true, verified_by: "Manual verification" },
  { regulation_index: 5, update_type: "new_regulation" as const, title: "Singapore Publishes World's First Agentic AI Governance Framework", summary: "IMDA published the Model AI Governance Framework for Agentic AI Systems on January 22, 2026.", source_url: "https://www.imda.gov.sg", verified: true, verified_by: "Manual verification" },
  { regulation_index: 4, update_type: "status_change" as const, title: "Canada's AIDA Dies as Parliament Prorogued", summary: "Bill C-27 died on January 6, 2025, when PM Trudeau prorogued Parliament. Canada has no dedicated federal AI legislation.", source_url: "https://www.parl.ca/legisinfo/en/bill/44-1/c-27", verified: true, verified_by: "Manual verification" },
  { regulation_index: 10, update_type: "amendment" as const, title: "California AI Transparency Act Effective Date Delayed to August 2026", summary: "AB 853 delayed the effective date of SB 942 from January 1, 2026, to August 2, 2026.", source_url: "https://leginfo.legislature.ca.gov", verified: true, verified_by: "Manual verification" },
  { regulation_index: 12, update_type: "new_regulation" as const, title: "Connecticut AI Act Enacted", summary: "Connecticut enacted SB 2 (Public Act 24-148), requiring impact assessments and consumer notification for high-risk AI systems. Effective February 1, 2026.", source_url: "https://www.cga.ct.gov", verified: true, verified_by: "Manual verification" },
  { regulation_index: 17, update_type: "new_regulation" as const, title: "South Korea Passes AI Basic Act", summary: "South Korea's National Assembly passed the AI Basic Act in December 2024, establishing a comprehensive framework for AI governance effective January 2026.", source_url: "https://www.law.go.kr", verified: true, verified_by: "Manual verification" },
  { regulation_index: 19, update_type: "new_regulation" as const, title: "China's Generative AI Regulations in Effect", summary: "China's Interim Measures for Generative AI became effective August 15, 2023, requiring content compliance and algorithm registration.", source_url: "http://www.cac.gov.cn", verified: true, verified_by: "Manual verification" },
  { regulation_index: 27, update_type: "status_change" as const, title: "EU DORA Enters Into Force", summary: "The Digital Operational Resilience Act became applicable on January 17, 2025, requiring financial institutions to manage AI/ICT risks.", source_url: "https://eur-lex.europa.eu", verified: true, verified_by: "Manual verification" },
  { regulation_index: 33, update_type: "new_regulation" as const, title: "Council of Europe AI Treaty Opened for Signature", summary: "The first legally binding international AI treaty was opened for signature on September 5, 2024.", source_url: "https://www.coe.int", verified: true, verified_by: "Manual verification" },
];
